USE [StudyRoomKiosk]
GO

/****** Object:  Table [dbo].[TBL_SEAT]    Script Date: 2020-05-14 ¿ÀÈÄ 7:25:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBL_SEAT](
	[seatNo] [varchar](2) NOT NULL,
	[status] [bit] NULL,
 CONSTRAINT [PK_TBL_SEAT] PRIMARY KEY CLUSTERED 
(
	[seatNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


